// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_LOGIN;
struct C_LOGINDefaultTypeInternal;
extern C_LOGINDefaultTypeInternal _C_LOGIN_default_instance_;
class C_PLAYER_ACTION_SYNC;
struct C_PLAYER_ACTION_SYNCDefaultTypeInternal;
extern C_PLAYER_ACTION_SYNCDefaultTypeInternal _C_PLAYER_ACTION_SYNC_default_instance_;
class C_PLAYER_ACTION_SYNC_MATRIX;
struct C_PLAYER_ACTION_SYNC_MATRIXDefaultTypeInternal;
extern C_PLAYER_ACTION_SYNC_MATRIXDefaultTypeInternal _C_PLAYER_ACTION_SYNC_MATRIX_default_instance_;
class S_LOGIN;
struct S_LOGINDefaultTypeInternal;
extern S_LOGINDefaultTypeInternal _S_LOGIN_default_instance_;
class S_PLAYER_ACTION_SYNC;
struct S_PLAYER_ACTION_SYNCDefaultTypeInternal;
extern S_PLAYER_ACTION_SYNCDefaultTypeInternal _S_PLAYER_ACTION_SYNC_default_instance_;
class S_PLAYER_ACTION_SYNC_MATRIX;
struct S_PLAYER_ACTION_SYNC_MATRIXDefaultTypeInternal;
extern S_PLAYER_ACTION_SYNC_MATRIXDefaultTypeInternal _S_PLAYER_ACTION_SYNC_MATRIX_default_instance_;
class S_PLAYER_EXIT;
struct S_PLAYER_EXITDefaultTypeInternal;
extern S_PLAYER_EXITDefaultTypeInternal _S_PLAYER_EXIT_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_LOGIN* Arena::CreateMaybeMessage<::Protocol::C_LOGIN>(Arena*);
template<> ::Protocol::C_PLAYER_ACTION_SYNC* Arena::CreateMaybeMessage<::Protocol::C_PLAYER_ACTION_SYNC>(Arena*);
template<> ::Protocol::C_PLAYER_ACTION_SYNC_MATRIX* Arena::CreateMaybeMessage<::Protocol::C_PLAYER_ACTION_SYNC_MATRIX>(Arena*);
template<> ::Protocol::S_LOGIN* Arena::CreateMaybeMessage<::Protocol::S_LOGIN>(Arena*);
template<> ::Protocol::S_PLAYER_ACTION_SYNC* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_ACTION_SYNC>(Arena*);
template<> ::Protocol::S_PLAYER_ACTION_SYNC_MATRIX* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_ACTION_SYNC_MATRIX>(Arena*);
template<> ::Protocol::S_PLAYER_EXIT* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_EXIT>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Protocol.C_LOGIN) */ {
 public:
  inline C_LOGIN() : C_LOGIN(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_LOGIN(const C_LOGIN& from);
  C_LOGIN(C_LOGIN&& from) noexcept
    : C_LOGIN() {
    *this = ::std::move(from);
  }

  inline C_LOGIN& operator=(const C_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOGIN& operator=(C_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LOGIN* internal_default_instance() {
    return reinterpret_cast<const C_LOGIN*>(
               &_C_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_LOGIN& a, C_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(C_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C_LOGIN& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C_LOGIN& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_LOGIN";
  }
  protected:
  explicit C_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_LOGIN) */ {
 public:
  inline S_LOGIN() : S_LOGIN(nullptr) {}
  ~S_LOGIN() override;
  explicit PROTOBUF_CONSTEXPR S_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_LOGIN(const S_LOGIN& from);
  S_LOGIN(S_LOGIN&& from) noexcept
    : S_LOGIN() {
    *this = ::std::move(from);
  }

  inline S_LOGIN& operator=(const S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOGIN& operator=(S_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LOGIN* internal_default_instance() {
    return reinterpret_cast<const S_LOGIN*>(
               &_S_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_LOGIN& a, S_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_LOGIN& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_LOGIN& from) {
    S_LOGIN::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_LOGIN* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_LOGIN";
  }
  protected:
  explicit S_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIDFieldNumber = 1,
  };
  // uint32 playerID = 1;
  void clear_playerid();
  uint32_t playerid() const;
  void set_playerid(uint32_t value);
  private:
  uint32_t _internal_playerid() const;
  void _internal_set_playerid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playerid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_EXIT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_EXIT) */ {
 public:
  inline S_PLAYER_EXIT() : S_PLAYER_EXIT(nullptr) {}
  ~S_PLAYER_EXIT() override;
  explicit PROTOBUF_CONSTEXPR S_PLAYER_EXIT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_EXIT(const S_PLAYER_EXIT& from);
  S_PLAYER_EXIT(S_PLAYER_EXIT&& from) noexcept
    : S_PLAYER_EXIT() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_EXIT& operator=(const S_PLAYER_EXIT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_EXIT& operator=(S_PLAYER_EXIT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_EXIT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_EXIT* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_EXIT*>(
               &_S_PLAYER_EXIT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S_PLAYER_EXIT& a, S_PLAYER_EXIT& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_EXIT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_EXIT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_PLAYER_EXIT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_PLAYER_EXIT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_PLAYER_EXIT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_PLAYER_EXIT& from) {
    S_PLAYER_EXIT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_EXIT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_EXIT";
  }
  protected:
  explicit S_PLAYER_EXIT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
  };
  // .Protocol.Player player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::Protocol::Player& player() const;
  PROTOBUF_NODISCARD ::Protocol::Player* release_player();
  ::Protocol::Player* mutable_player();
  void set_allocated_player(::Protocol::Player* player);
  private:
  const ::Protocol::Player& _internal_player() const;
  ::Protocol::Player* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::Protocol::Player* player);
  ::Protocol::Player* unsafe_arena_release_player();

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_EXIT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Player* player_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_PLAYER_ACTION_SYNC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_PLAYER_ACTION_SYNC) */ {
 public:
  inline C_PLAYER_ACTION_SYNC() : C_PLAYER_ACTION_SYNC(nullptr) {}
  ~C_PLAYER_ACTION_SYNC() override;
  explicit PROTOBUF_CONSTEXPR C_PLAYER_ACTION_SYNC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_PLAYER_ACTION_SYNC(const C_PLAYER_ACTION_SYNC& from);
  C_PLAYER_ACTION_SYNC(C_PLAYER_ACTION_SYNC&& from) noexcept
    : C_PLAYER_ACTION_SYNC() {
    *this = ::std::move(from);
  }

  inline C_PLAYER_ACTION_SYNC& operator=(const C_PLAYER_ACTION_SYNC& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_PLAYER_ACTION_SYNC& operator=(C_PLAYER_ACTION_SYNC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_PLAYER_ACTION_SYNC& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_PLAYER_ACTION_SYNC* internal_default_instance() {
    return reinterpret_cast<const C_PLAYER_ACTION_SYNC*>(
               &_C_PLAYER_ACTION_SYNC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(C_PLAYER_ACTION_SYNC& a, C_PLAYER_ACTION_SYNC& b) {
    a.Swap(&b);
  }
  inline void Swap(C_PLAYER_ACTION_SYNC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_PLAYER_ACTION_SYNC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_PLAYER_ACTION_SYNC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_PLAYER_ACTION_SYNC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_PLAYER_ACTION_SYNC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_PLAYER_ACTION_SYNC& from) {
    C_PLAYER_ACTION_SYNC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_PLAYER_ACTION_SYNC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_PLAYER_ACTION_SYNC";
  }
  protected:
  explicit C_PLAYER_ACTION_SYNC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
    kSyncDataFieldNumber = 2,
  };
  // .Protocol.Player player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::Protocol::Player& player() const;
  PROTOBUF_NODISCARD ::Protocol::Player* release_player();
  ::Protocol::Player* mutable_player();
  void set_allocated_player(::Protocol::Player* player);
  private:
  const ::Protocol::Player& _internal_player() const;
  ::Protocol::Player* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::Protocol::Player* player);
  ::Protocol::Player* unsafe_arena_release_player();

  // .Protocol.PlayerSyncData syncData = 2;
  bool has_syncdata() const;
  private:
  bool _internal_has_syncdata() const;
  public:
  void clear_syncdata();
  const ::Protocol::PlayerSyncData& syncdata() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerSyncData* release_syncdata();
  ::Protocol::PlayerSyncData* mutable_syncdata();
  void set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata);
  private:
  const ::Protocol::PlayerSyncData& _internal_syncdata() const;
  ::Protocol::PlayerSyncData* _internal_mutable_syncdata();
  public:
  void unsafe_arena_set_allocated_syncdata(
      ::Protocol::PlayerSyncData* syncdata);
  ::Protocol::PlayerSyncData* unsafe_arena_release_syncdata();

  // @@protoc_insertion_point(class_scope:Protocol.C_PLAYER_ACTION_SYNC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Player* player_;
    ::Protocol::PlayerSyncData* syncdata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_ACTION_SYNC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_ACTION_SYNC) */ {
 public:
  inline S_PLAYER_ACTION_SYNC() : S_PLAYER_ACTION_SYNC(nullptr) {}
  ~S_PLAYER_ACTION_SYNC() override;
  explicit PROTOBUF_CONSTEXPR S_PLAYER_ACTION_SYNC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_ACTION_SYNC(const S_PLAYER_ACTION_SYNC& from);
  S_PLAYER_ACTION_SYNC(S_PLAYER_ACTION_SYNC&& from) noexcept
    : S_PLAYER_ACTION_SYNC() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_ACTION_SYNC& operator=(const S_PLAYER_ACTION_SYNC& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_ACTION_SYNC& operator=(S_PLAYER_ACTION_SYNC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_ACTION_SYNC& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_ACTION_SYNC* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_ACTION_SYNC*>(
               &_S_PLAYER_ACTION_SYNC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(S_PLAYER_ACTION_SYNC& a, S_PLAYER_ACTION_SYNC& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_ACTION_SYNC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_ACTION_SYNC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_PLAYER_ACTION_SYNC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_PLAYER_ACTION_SYNC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_PLAYER_ACTION_SYNC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_PLAYER_ACTION_SYNC& from) {
    S_PLAYER_ACTION_SYNC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_ACTION_SYNC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_ACTION_SYNC";
  }
  protected:
  explicit S_PLAYER_ACTION_SYNC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
    kSyncDataFieldNumber = 2,
  };
  // .Protocol.Player player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::Protocol::Player& player() const;
  PROTOBUF_NODISCARD ::Protocol::Player* release_player();
  ::Protocol::Player* mutable_player();
  void set_allocated_player(::Protocol::Player* player);
  private:
  const ::Protocol::Player& _internal_player() const;
  ::Protocol::Player* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::Protocol::Player* player);
  ::Protocol::Player* unsafe_arena_release_player();

  // .Protocol.PlayerSyncData syncData = 2;
  bool has_syncdata() const;
  private:
  bool _internal_has_syncdata() const;
  public:
  void clear_syncdata();
  const ::Protocol::PlayerSyncData& syncdata() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerSyncData* release_syncdata();
  ::Protocol::PlayerSyncData* mutable_syncdata();
  void set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata);
  private:
  const ::Protocol::PlayerSyncData& _internal_syncdata() const;
  ::Protocol::PlayerSyncData* _internal_mutable_syncdata();
  public:
  void unsafe_arena_set_allocated_syncdata(
      ::Protocol::PlayerSyncData* syncdata);
  ::Protocol::PlayerSyncData* unsafe_arena_release_syncdata();

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_ACTION_SYNC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Player* player_;
    ::Protocol::PlayerSyncData* syncdata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_PLAYER_ACTION_SYNC_MATRIX final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_PLAYER_ACTION_SYNC_MATRIX) */ {
 public:
  inline C_PLAYER_ACTION_SYNC_MATRIX() : C_PLAYER_ACTION_SYNC_MATRIX(nullptr) {}
  ~C_PLAYER_ACTION_SYNC_MATRIX() override;
  explicit PROTOBUF_CONSTEXPR C_PLAYER_ACTION_SYNC_MATRIX(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_PLAYER_ACTION_SYNC_MATRIX(const C_PLAYER_ACTION_SYNC_MATRIX& from);
  C_PLAYER_ACTION_SYNC_MATRIX(C_PLAYER_ACTION_SYNC_MATRIX&& from) noexcept
    : C_PLAYER_ACTION_SYNC_MATRIX() {
    *this = ::std::move(from);
  }

  inline C_PLAYER_ACTION_SYNC_MATRIX& operator=(const C_PLAYER_ACTION_SYNC_MATRIX& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_PLAYER_ACTION_SYNC_MATRIX& operator=(C_PLAYER_ACTION_SYNC_MATRIX&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_PLAYER_ACTION_SYNC_MATRIX& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_PLAYER_ACTION_SYNC_MATRIX* internal_default_instance() {
    return reinterpret_cast<const C_PLAYER_ACTION_SYNC_MATRIX*>(
               &_C_PLAYER_ACTION_SYNC_MATRIX_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(C_PLAYER_ACTION_SYNC_MATRIX& a, C_PLAYER_ACTION_SYNC_MATRIX& b) {
    a.Swap(&b);
  }
  inline void Swap(C_PLAYER_ACTION_SYNC_MATRIX* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_PLAYER_ACTION_SYNC_MATRIX* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_PLAYER_ACTION_SYNC_MATRIX* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_PLAYER_ACTION_SYNC_MATRIX>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_PLAYER_ACTION_SYNC_MATRIX& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_PLAYER_ACTION_SYNC_MATRIX& from) {
    C_PLAYER_ACTION_SYNC_MATRIX::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_PLAYER_ACTION_SYNC_MATRIX* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_PLAYER_ACTION_SYNC_MATRIX";
  }
  protected:
  explicit C_PLAYER_ACTION_SYNC_MATRIX(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
    kSyncDataFieldNumber = 2,
    kWorldFieldNumber = 3,
  };
  // .Protocol.Player player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::Protocol::Player& player() const;
  PROTOBUF_NODISCARD ::Protocol::Player* release_player();
  ::Protocol::Player* mutable_player();
  void set_allocated_player(::Protocol::Player* player);
  private:
  const ::Protocol::Player& _internal_player() const;
  ::Protocol::Player* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::Protocol::Player* player);
  ::Protocol::Player* unsafe_arena_release_player();

  // .Protocol.PlayerSyncData syncData = 2;
  bool has_syncdata() const;
  private:
  bool _internal_has_syncdata() const;
  public:
  void clear_syncdata();
  const ::Protocol::PlayerSyncData& syncdata() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerSyncData* release_syncdata();
  ::Protocol::PlayerSyncData* mutable_syncdata();
  void set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata);
  private:
  const ::Protocol::PlayerSyncData& _internal_syncdata() const;
  ::Protocol::PlayerSyncData* _internal_mutable_syncdata();
  public:
  void unsafe_arena_set_allocated_syncdata(
      ::Protocol::PlayerSyncData* syncdata);
  ::Protocol::PlayerSyncData* unsafe_arena_release_syncdata();

  // .Protocol.Matrix world = 3;
  bool has_world() const;
  private:
  bool _internal_has_world() const;
  public:
  void clear_world();
  const ::Protocol::Matrix& world() const;
  PROTOBUF_NODISCARD ::Protocol::Matrix* release_world();
  ::Protocol::Matrix* mutable_world();
  void set_allocated_world(::Protocol::Matrix* world);
  private:
  const ::Protocol::Matrix& _internal_world() const;
  ::Protocol::Matrix* _internal_mutable_world();
  public:
  void unsafe_arena_set_allocated_world(
      ::Protocol::Matrix* world);
  ::Protocol::Matrix* unsafe_arena_release_world();

  // @@protoc_insertion_point(class_scope:Protocol.C_PLAYER_ACTION_SYNC_MATRIX)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Player* player_;
    ::Protocol::PlayerSyncData* syncdata_;
    ::Protocol::Matrix* world_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_ACTION_SYNC_MATRIX final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_ACTION_SYNC_MATRIX) */ {
 public:
  inline S_PLAYER_ACTION_SYNC_MATRIX() : S_PLAYER_ACTION_SYNC_MATRIX(nullptr) {}
  ~S_PLAYER_ACTION_SYNC_MATRIX() override;
  explicit PROTOBUF_CONSTEXPR S_PLAYER_ACTION_SYNC_MATRIX(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_ACTION_SYNC_MATRIX(const S_PLAYER_ACTION_SYNC_MATRIX& from);
  S_PLAYER_ACTION_SYNC_MATRIX(S_PLAYER_ACTION_SYNC_MATRIX&& from) noexcept
    : S_PLAYER_ACTION_SYNC_MATRIX() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_ACTION_SYNC_MATRIX& operator=(const S_PLAYER_ACTION_SYNC_MATRIX& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_ACTION_SYNC_MATRIX& operator=(S_PLAYER_ACTION_SYNC_MATRIX&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_ACTION_SYNC_MATRIX& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_ACTION_SYNC_MATRIX* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_ACTION_SYNC_MATRIX*>(
               &_S_PLAYER_ACTION_SYNC_MATRIX_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S_PLAYER_ACTION_SYNC_MATRIX& a, S_PLAYER_ACTION_SYNC_MATRIX& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_ACTION_SYNC_MATRIX* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_ACTION_SYNC_MATRIX* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_PLAYER_ACTION_SYNC_MATRIX* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_PLAYER_ACTION_SYNC_MATRIX>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_PLAYER_ACTION_SYNC_MATRIX& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_PLAYER_ACTION_SYNC_MATRIX& from) {
    S_PLAYER_ACTION_SYNC_MATRIX::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_ACTION_SYNC_MATRIX* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_ACTION_SYNC_MATRIX";
  }
  protected:
  explicit S_PLAYER_ACTION_SYNC_MATRIX(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerFieldNumber = 1,
    kSyncDataFieldNumber = 2,
    kWorldFieldNumber = 3,
  };
  // .Protocol.Player player = 1;
  bool has_player() const;
  private:
  bool _internal_has_player() const;
  public:
  void clear_player();
  const ::Protocol::Player& player() const;
  PROTOBUF_NODISCARD ::Protocol::Player* release_player();
  ::Protocol::Player* mutable_player();
  void set_allocated_player(::Protocol::Player* player);
  private:
  const ::Protocol::Player& _internal_player() const;
  ::Protocol::Player* _internal_mutable_player();
  public:
  void unsafe_arena_set_allocated_player(
      ::Protocol::Player* player);
  ::Protocol::Player* unsafe_arena_release_player();

  // .Protocol.PlayerSyncData syncData = 2;
  bool has_syncdata() const;
  private:
  bool _internal_has_syncdata() const;
  public:
  void clear_syncdata();
  const ::Protocol::PlayerSyncData& syncdata() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerSyncData* release_syncdata();
  ::Protocol::PlayerSyncData* mutable_syncdata();
  void set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata);
  private:
  const ::Protocol::PlayerSyncData& _internal_syncdata() const;
  ::Protocol::PlayerSyncData* _internal_mutable_syncdata();
  public:
  void unsafe_arena_set_allocated_syncdata(
      ::Protocol::PlayerSyncData* syncdata);
  ::Protocol::PlayerSyncData* unsafe_arena_release_syncdata();

  // .Protocol.Matrix world = 3;
  bool has_world() const;
  private:
  bool _internal_has_world() const;
  public:
  void clear_world();
  const ::Protocol::Matrix& world() const;
  PROTOBUF_NODISCARD ::Protocol::Matrix* release_world();
  ::Protocol::Matrix* mutable_world();
  void set_allocated_world(::Protocol::Matrix* world);
  private:
  const ::Protocol::Matrix& _internal_world() const;
  ::Protocol::Matrix* _internal_mutable_world();
  public:
  void unsafe_arena_set_allocated_world(
      ::Protocol::Matrix* world);
  ::Protocol::Matrix* unsafe_arena_release_world();

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_ACTION_SYNC_MATRIX)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Player* player_;
    ::Protocol::PlayerSyncData* syncdata_;
    ::Protocol::Matrix* world_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_LOGIN

// -------------------------------------------------------------------

// S_LOGIN

// uint32 playerID = 1;
inline void S_LOGIN::clear_playerid() {
  _impl_.playerid_ = 0u;
}
inline uint32_t S_LOGIN::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint32_t S_LOGIN::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.playerID)
  return _internal_playerid();
}
inline void S_LOGIN::_internal_set_playerid(uint32_t value) {
  
  _impl_.playerid_ = value;
}
inline void S_LOGIN::set_playerid(uint32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.playerID)
}

// -------------------------------------------------------------------

// S_PLAYER_EXIT

// .Protocol.Player player = 1;
inline bool S_PLAYER_EXIT::_internal_has_player() const {
  return this != internal_default_instance() && _impl_.player_ != nullptr;
}
inline bool S_PLAYER_EXIT::has_player() const {
  return _internal_has_player();
}
inline const ::Protocol::Player& S_PLAYER_EXIT::_internal_player() const {
  const ::Protocol::Player* p = _impl_.player_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& S_PLAYER_EXIT::player() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_EXIT.player)
  return _internal_player();
}
inline void S_PLAYER_EXIT::unsafe_arena_set_allocated_player(
    ::Protocol::Player* player) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  _impl_.player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_EXIT.player)
}
inline ::Protocol::Player* S_PLAYER_EXIT::release_player() {
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Player* S_PLAYER_EXIT::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_EXIT.player)
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
  return temp;
}
inline ::Protocol::Player* S_PLAYER_EXIT::_internal_mutable_player() {
  
  if (_impl_.player_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    _impl_.player_ = p;
  }
  return _impl_.player_;
}
inline ::Protocol::Player* S_PLAYER_EXIT::mutable_player() {
  ::Protocol::Player* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_EXIT.player)
  return _msg;
}
inline void S_PLAYER_EXIT::set_allocated_player(::Protocol::Player* player) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  if (player) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player));
    if (message_arena != submessage_arena) {
      player = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_ = player;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_EXIT.player)
}

// -------------------------------------------------------------------

// C_PLAYER_ACTION_SYNC

// .Protocol.Player player = 1;
inline bool C_PLAYER_ACTION_SYNC::_internal_has_player() const {
  return this != internal_default_instance() && _impl_.player_ != nullptr;
}
inline bool C_PLAYER_ACTION_SYNC::has_player() const {
  return _internal_has_player();
}
inline const ::Protocol::Player& C_PLAYER_ACTION_SYNC::_internal_player() const {
  const ::Protocol::Player* p = _impl_.player_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& C_PLAYER_ACTION_SYNC::player() const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_ACTION_SYNC.player)
  return _internal_player();
}
inline void C_PLAYER_ACTION_SYNC::unsafe_arena_set_allocated_player(
    ::Protocol::Player* player) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  _impl_.player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_PLAYER_ACTION_SYNC.player)
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC::release_player() {
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_release:Protocol.C_PLAYER_ACTION_SYNC.player)
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
  return temp;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC::_internal_mutable_player() {
  
  if (_impl_.player_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    _impl_.player_ = p;
  }
  return _impl_.player_;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC::mutable_player() {
  ::Protocol::Player* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_ACTION_SYNC.player)
  return _msg;
}
inline void C_PLAYER_ACTION_SYNC::set_allocated_player(::Protocol::Player* player) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  if (player) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player));
    if (message_arena != submessage_arena) {
      player = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_ = player;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_PLAYER_ACTION_SYNC.player)
}

// .Protocol.PlayerSyncData syncData = 2;
inline bool C_PLAYER_ACTION_SYNC::_internal_has_syncdata() const {
  return this != internal_default_instance() && _impl_.syncdata_ != nullptr;
}
inline bool C_PLAYER_ACTION_SYNC::has_syncdata() const {
  return _internal_has_syncdata();
}
inline const ::Protocol::PlayerSyncData& C_PLAYER_ACTION_SYNC::_internal_syncdata() const {
  const ::Protocol::PlayerSyncData* p = _impl_.syncdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerSyncData&>(
      ::Protocol::_PlayerSyncData_default_instance_);
}
inline const ::Protocol::PlayerSyncData& C_PLAYER_ACTION_SYNC::syncdata() const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_ACTION_SYNC.syncData)
  return _internal_syncdata();
}
inline void C_PLAYER_ACTION_SYNC::unsafe_arena_set_allocated_syncdata(
    ::Protocol::PlayerSyncData* syncdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  _impl_.syncdata_ = syncdata;
  if (syncdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_PLAYER_ACTION_SYNC.syncData)
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC::release_syncdata() {
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC::unsafe_arena_release_syncdata() {
  // @@protoc_insertion_point(field_release:Protocol.C_PLAYER_ACTION_SYNC.syncData)
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC::_internal_mutable_syncdata() {
  
  if (_impl_.syncdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerSyncData>(GetArenaForAllocation());
    _impl_.syncdata_ = p;
  }
  return _impl_.syncdata_;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC::mutable_syncdata() {
  ::Protocol::PlayerSyncData* _msg = _internal_mutable_syncdata();
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_ACTION_SYNC.syncData)
  return _msg;
}
inline void C_PLAYER_ACTION_SYNC::set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  if (syncdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(syncdata));
    if (message_arena != submessage_arena) {
      syncdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, syncdata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.syncdata_ = syncdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_PLAYER_ACTION_SYNC.syncData)
}

// -------------------------------------------------------------------

// S_PLAYER_ACTION_SYNC

// .Protocol.Player player = 1;
inline bool S_PLAYER_ACTION_SYNC::_internal_has_player() const {
  return this != internal_default_instance() && _impl_.player_ != nullptr;
}
inline bool S_PLAYER_ACTION_SYNC::has_player() const {
  return _internal_has_player();
}
inline const ::Protocol::Player& S_PLAYER_ACTION_SYNC::_internal_player() const {
  const ::Protocol::Player* p = _impl_.player_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& S_PLAYER_ACTION_SYNC::player() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ACTION_SYNC.player)
  return _internal_player();
}
inline void S_PLAYER_ACTION_SYNC::unsafe_arena_set_allocated_player(
    ::Protocol::Player* player) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  _impl_.player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_ACTION_SYNC.player)
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC::release_player() {
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_ACTION_SYNC.player)
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
  return temp;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC::_internal_mutable_player() {
  
  if (_impl_.player_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    _impl_.player_ = p;
  }
  return _impl_.player_;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC::mutable_player() {
  ::Protocol::Player* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ACTION_SYNC.player)
  return _msg;
}
inline void S_PLAYER_ACTION_SYNC::set_allocated_player(::Protocol::Player* player) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  if (player) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player));
    if (message_arena != submessage_arena) {
      player = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_ = player;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_ACTION_SYNC.player)
}

// .Protocol.PlayerSyncData syncData = 2;
inline bool S_PLAYER_ACTION_SYNC::_internal_has_syncdata() const {
  return this != internal_default_instance() && _impl_.syncdata_ != nullptr;
}
inline bool S_PLAYER_ACTION_SYNC::has_syncdata() const {
  return _internal_has_syncdata();
}
inline const ::Protocol::PlayerSyncData& S_PLAYER_ACTION_SYNC::_internal_syncdata() const {
  const ::Protocol::PlayerSyncData* p = _impl_.syncdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerSyncData&>(
      ::Protocol::_PlayerSyncData_default_instance_);
}
inline const ::Protocol::PlayerSyncData& S_PLAYER_ACTION_SYNC::syncdata() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ACTION_SYNC.syncData)
  return _internal_syncdata();
}
inline void S_PLAYER_ACTION_SYNC::unsafe_arena_set_allocated_syncdata(
    ::Protocol::PlayerSyncData* syncdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  _impl_.syncdata_ = syncdata;
  if (syncdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_ACTION_SYNC.syncData)
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC::release_syncdata() {
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC::unsafe_arena_release_syncdata() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_ACTION_SYNC.syncData)
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC::_internal_mutable_syncdata() {
  
  if (_impl_.syncdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerSyncData>(GetArenaForAllocation());
    _impl_.syncdata_ = p;
  }
  return _impl_.syncdata_;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC::mutable_syncdata() {
  ::Protocol::PlayerSyncData* _msg = _internal_mutable_syncdata();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ACTION_SYNC.syncData)
  return _msg;
}
inline void S_PLAYER_ACTION_SYNC::set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  if (syncdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(syncdata));
    if (message_arena != submessage_arena) {
      syncdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, syncdata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.syncdata_ = syncdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_ACTION_SYNC.syncData)
}

// -------------------------------------------------------------------

// C_PLAYER_ACTION_SYNC_MATRIX

// .Protocol.Player player = 1;
inline bool C_PLAYER_ACTION_SYNC_MATRIX::_internal_has_player() const {
  return this != internal_default_instance() && _impl_.player_ != nullptr;
}
inline bool C_PLAYER_ACTION_SYNC_MATRIX::has_player() const {
  return _internal_has_player();
}
inline const ::Protocol::Player& C_PLAYER_ACTION_SYNC_MATRIX::_internal_player() const {
  const ::Protocol::Player* p = _impl_.player_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& C_PLAYER_ACTION_SYNC_MATRIX::player() const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.player)
  return _internal_player();
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_player(
    ::Protocol::Player* player) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  _impl_.player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.player)
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC_MATRIX::release_player() {
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_release:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.player)
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
  return temp;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_player() {
  
  if (_impl_.player_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    _impl_.player_ = p;
  }
  return _impl_.player_;
}
inline ::Protocol::Player* C_PLAYER_ACTION_SYNC_MATRIX::mutable_player() {
  ::Protocol::Player* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.player)
  return _msg;
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::set_allocated_player(::Protocol::Player* player) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  if (player) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player));
    if (message_arena != submessage_arena) {
      player = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_ = player;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.player)
}

// .Protocol.PlayerSyncData syncData = 2;
inline bool C_PLAYER_ACTION_SYNC_MATRIX::_internal_has_syncdata() const {
  return this != internal_default_instance() && _impl_.syncdata_ != nullptr;
}
inline bool C_PLAYER_ACTION_SYNC_MATRIX::has_syncdata() const {
  return _internal_has_syncdata();
}
inline const ::Protocol::PlayerSyncData& C_PLAYER_ACTION_SYNC_MATRIX::_internal_syncdata() const {
  const ::Protocol::PlayerSyncData* p = _impl_.syncdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerSyncData&>(
      ::Protocol::_PlayerSyncData_default_instance_);
}
inline const ::Protocol::PlayerSyncData& C_PLAYER_ACTION_SYNC_MATRIX::syncdata() const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.syncData)
  return _internal_syncdata();
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_syncdata(
    ::Protocol::PlayerSyncData* syncdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  _impl_.syncdata_ = syncdata;
  if (syncdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.syncData)
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC_MATRIX::release_syncdata() {
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_syncdata() {
  // @@protoc_insertion_point(field_release:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.syncData)
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_syncdata() {
  
  if (_impl_.syncdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerSyncData>(GetArenaForAllocation());
    _impl_.syncdata_ = p;
  }
  return _impl_.syncdata_;
}
inline ::Protocol::PlayerSyncData* C_PLAYER_ACTION_SYNC_MATRIX::mutable_syncdata() {
  ::Protocol::PlayerSyncData* _msg = _internal_mutable_syncdata();
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.syncData)
  return _msg;
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  if (syncdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(syncdata));
    if (message_arena != submessage_arena) {
      syncdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, syncdata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.syncdata_ = syncdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.syncData)
}

// .Protocol.Matrix world = 3;
inline bool C_PLAYER_ACTION_SYNC_MATRIX::_internal_has_world() const {
  return this != internal_default_instance() && _impl_.world_ != nullptr;
}
inline bool C_PLAYER_ACTION_SYNC_MATRIX::has_world() const {
  return _internal_has_world();
}
inline const ::Protocol::Matrix& C_PLAYER_ACTION_SYNC_MATRIX::_internal_world() const {
  const ::Protocol::Matrix* p = _impl_.world_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Matrix&>(
      ::Protocol::_Matrix_default_instance_);
}
inline const ::Protocol::Matrix& C_PLAYER_ACTION_SYNC_MATRIX::world() const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.world)
  return _internal_world();
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_world(
    ::Protocol::Matrix* world) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.world_);
  }
  _impl_.world_ = world;
  if (world) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.world)
}
inline ::Protocol::Matrix* C_PLAYER_ACTION_SYNC_MATRIX::release_world() {
  
  ::Protocol::Matrix* temp = _impl_.world_;
  _impl_.world_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Matrix* C_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_world() {
  // @@protoc_insertion_point(field_release:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.world)
  
  ::Protocol::Matrix* temp = _impl_.world_;
  _impl_.world_ = nullptr;
  return temp;
}
inline ::Protocol::Matrix* C_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_world() {
  
  if (_impl_.world_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Matrix>(GetArenaForAllocation());
    _impl_.world_ = p;
  }
  return _impl_.world_;
}
inline ::Protocol::Matrix* C_PLAYER_ACTION_SYNC_MATRIX::mutable_world() {
  ::Protocol::Matrix* _msg = _internal_mutable_world();
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.world)
  return _msg;
}
inline void C_PLAYER_ACTION_SYNC_MATRIX::set_allocated_world(::Protocol::Matrix* world) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.world_);
  }
  if (world) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(world));
    if (message_arena != submessage_arena) {
      world = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, world, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.world_ = world;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_PLAYER_ACTION_SYNC_MATRIX.world)
}

// -------------------------------------------------------------------

// S_PLAYER_ACTION_SYNC_MATRIX

// .Protocol.Player player = 1;
inline bool S_PLAYER_ACTION_SYNC_MATRIX::_internal_has_player() const {
  return this != internal_default_instance() && _impl_.player_ != nullptr;
}
inline bool S_PLAYER_ACTION_SYNC_MATRIX::has_player() const {
  return _internal_has_player();
}
inline const ::Protocol::Player& S_PLAYER_ACTION_SYNC_MATRIX::_internal_player() const {
  const ::Protocol::Player* p = _impl_.player_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& S_PLAYER_ACTION_SYNC_MATRIX::player() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.player)
  return _internal_player();
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_player(
    ::Protocol::Player* player) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  _impl_.player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.player)
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC_MATRIX::release_player() {
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_player() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.player)
  
  ::Protocol::Player* temp = _impl_.player_;
  _impl_.player_ = nullptr;
  return temp;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_player() {
  
  if (_impl_.player_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    _impl_.player_ = p;
  }
  return _impl_.player_;
}
inline ::Protocol::Player* S_PLAYER_ACTION_SYNC_MATRIX::mutable_player() {
  ::Protocol::Player* _msg = _internal_mutable_player();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.player)
  return _msg;
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::set_allocated_player(::Protocol::Player* player) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_);
  }
  if (player) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(player));
    if (message_arena != submessage_arena) {
      player = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.player_ = player;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.player)
}

// .Protocol.PlayerSyncData syncData = 2;
inline bool S_PLAYER_ACTION_SYNC_MATRIX::_internal_has_syncdata() const {
  return this != internal_default_instance() && _impl_.syncdata_ != nullptr;
}
inline bool S_PLAYER_ACTION_SYNC_MATRIX::has_syncdata() const {
  return _internal_has_syncdata();
}
inline const ::Protocol::PlayerSyncData& S_PLAYER_ACTION_SYNC_MATRIX::_internal_syncdata() const {
  const ::Protocol::PlayerSyncData* p = _impl_.syncdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerSyncData&>(
      ::Protocol::_PlayerSyncData_default_instance_);
}
inline const ::Protocol::PlayerSyncData& S_PLAYER_ACTION_SYNC_MATRIX::syncdata() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.syncData)
  return _internal_syncdata();
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_syncdata(
    ::Protocol::PlayerSyncData* syncdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  _impl_.syncdata_ = syncdata;
  if (syncdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.syncData)
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC_MATRIX::release_syncdata() {
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_syncdata() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.syncData)
  
  ::Protocol::PlayerSyncData* temp = _impl_.syncdata_;
  _impl_.syncdata_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_syncdata() {
  
  if (_impl_.syncdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerSyncData>(GetArenaForAllocation());
    _impl_.syncdata_ = p;
  }
  return _impl_.syncdata_;
}
inline ::Protocol::PlayerSyncData* S_PLAYER_ACTION_SYNC_MATRIX::mutable_syncdata() {
  ::Protocol::PlayerSyncData* _msg = _internal_mutable_syncdata();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.syncData)
  return _msg;
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::set_allocated_syncdata(::Protocol::PlayerSyncData* syncdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.syncdata_);
  }
  if (syncdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(syncdata));
    if (message_arena != submessage_arena) {
      syncdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, syncdata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.syncdata_ = syncdata;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.syncData)
}

// .Protocol.Matrix world = 3;
inline bool S_PLAYER_ACTION_SYNC_MATRIX::_internal_has_world() const {
  return this != internal_default_instance() && _impl_.world_ != nullptr;
}
inline bool S_PLAYER_ACTION_SYNC_MATRIX::has_world() const {
  return _internal_has_world();
}
inline const ::Protocol::Matrix& S_PLAYER_ACTION_SYNC_MATRIX::_internal_world() const {
  const ::Protocol::Matrix* p = _impl_.world_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Matrix&>(
      ::Protocol::_Matrix_default_instance_);
}
inline const ::Protocol::Matrix& S_PLAYER_ACTION_SYNC_MATRIX::world() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.world)
  return _internal_world();
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_set_allocated_world(
    ::Protocol::Matrix* world) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.world_);
  }
  _impl_.world_ = world;
  if (world) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.world)
}
inline ::Protocol::Matrix* S_PLAYER_ACTION_SYNC_MATRIX::release_world() {
  
  ::Protocol::Matrix* temp = _impl_.world_;
  _impl_.world_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Matrix* S_PLAYER_ACTION_SYNC_MATRIX::unsafe_arena_release_world() {
  // @@protoc_insertion_point(field_release:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.world)
  
  ::Protocol::Matrix* temp = _impl_.world_;
  _impl_.world_ = nullptr;
  return temp;
}
inline ::Protocol::Matrix* S_PLAYER_ACTION_SYNC_MATRIX::_internal_mutable_world() {
  
  if (_impl_.world_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Matrix>(GetArenaForAllocation());
    _impl_.world_ = p;
  }
  return _impl_.world_;
}
inline ::Protocol::Matrix* S_PLAYER_ACTION_SYNC_MATRIX::mutable_world() {
  ::Protocol::Matrix* _msg = _internal_mutable_world();
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.world)
  return _msg;
}
inline void S_PLAYER_ACTION_SYNC_MATRIX::set_allocated_world(::Protocol::Matrix* world) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.world_);
  }
  if (world) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(world));
    if (message_arena != submessage_arena) {
      world = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, world, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.world_ = world;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_PLAYER_ACTION_SYNC_MATRIX.world)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
